# Generated by Django 4.1.2 on 2025-11-19 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_add_origem_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome da Variável')),
                ('codigo', models.SlugField(max_length=100, unique=True, verbose_name='Código Único')),
                ('tipo_dado', models.CharField(choices=[('FLOAT', 'Número Decimal'), ('INTEGER', 'Número Inteiro'), ('STRING', 'Texto')], default='FLOAT', max_length=10, verbose_name='Tipo de Dado')),
                ('unidade_medida', models.CharField(blank=True, max_length=50, verbose_name='Unidade de Medida')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('valor_padrao_geral', models.JSONField(blank=True, default=dict, null=True, verbose_name='Valor Padrão Geral')),
                ('ativo', models.BooleanField(default=True, verbose_name='Variável Ativa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Variável Customizada',
                'verbose_name_plural': 'Variáveis Customizadas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TreeVariableValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.JSONField(verbose_name='Valor')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variaveis_customizadas', to='main.tree')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='main.treevariable')),
            ],
            options={
                'verbose_name': 'Valor de Variável',
                'verbose_name_plural': 'Valores de Variáveis',
                'unique_together': {('tree', 'variable')},
            },
        ),
        migrations.CreateModel(
            name='SpeciesVariableDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_padrao', models.JSONField(verbose_name='Valor Padrão')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variaveis_padrao', to='main.species')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_por_especie', to='main.treevariable')),
            ],
            options={
                'verbose_name': 'Valor Padrão por Espécie',
                'verbose_name_plural': 'Valores Padrão por Espécie',
                'unique_together': {('species', 'variable')},
            },
        ),
    ]
